package main

// Content data: prompts, responses, log vocab, metric names.
// All Japanese / English content. Pure data; no I/O.

// ============ LLM-style prompts and responses (left pane) ============

type Response struct {
	Prompt    string
	Thinking  string
	Chunks    []string // streamed in order; \n is included as needed
}

func responsesNormal() []*Response {
	return []*Response{
		{
			Prompt:   "Q3 のセグメント別 revenue ブリッジを institutional / retail / private banking で要約してください。",
			Thinking: "コンテキストを集約しています",
			Chunks: []string{
				"承知しました。",
				"Q3 のセグメント別 revenue ブリッジを",
				"institutional / retail / private banking の",
				"3 セグメントに分解して整理します。",
				"\n\n",
				"## エグゼクティブ・サマリー",
				"\n\n",
				"全体の Q3 revenue は ", "**¥ 38.4B**", "、",
				"前年同期比 ", "**+6.8%**", "[1]。",
				"セグメント別の貢献度は以下の通りです。",
				"\n\n",
				"## セグメント別貢献",
				"\n",
				"- **Institutional**: ", "¥ 17.2B (シェア 44.7%)、",
				"前年同期比 **+9.1%**", "[2]",
				"\n",
				"  - prime brokerage の活動量増が押し上げ",
				"\n",
				"  - block trading volume +14.5% YoY",
				"\n",
				"- **Retail**: ", "¥ 12.9B (シェア 33.6%)、",
				"前年同期比 **+3.2%**",
				"\n",
				"  - mortgage origination は為替中立で +5.8%",
				"\n",
				"  - card spend は YoY +2.1% と微増",
				"\n",
				"- **Private Banking**: ", "¥ 8.3B (シェア 21.6%)、",
				"前年同期比 **+8.4%**", "[3]",
				"\n",
				"  - net new money ¥ 142B",
				"\n",
				"  - 中期計画ガイダンス上限を +11% 上回る",
				"\n\n",
				"## 主要ドライバー",
				"\n\n",
				"> fee-based revenue 比率が",
				"前年同期比 **+220 bps** 改善し、",
				"市場リスクへの感応度を低減。",
				"今後 2 四半期の resilience 向上に寄与する見込み。",
				"\n\n",
				"## リスク・センサー",
				"\n",
				"- USD 強含みが継続した場合、",
				"non-USD revenue の YoY 成長率に",
				"**-180 から -240 bps** の影響",
				"\n",
				"- private banking の net new money は",
				"macro hedge の一部利下げ織り込みで",
				"Q4 にかけて減速の可能性 (信頼度 中)",
				"\n\n",
				"[1] internal-bi/q3-2026-revenue-snapshot rev=4d2",
				"\n",
				"[2] strategy/institutional-prime-brokerage-yoy",
				"\n",
				"[3] private-bank/nnm-tracker-202609",
			},
		},
		{
			Prompt:   "AUM の前年同期比成長率を地域別にまとめ、主要なアロケーション変化を抽出してください。",
			Thinking: "AUM tracker を参照しています",
			Chunks: []string{
				"AUM の地域別成長率を、",
				"Q3 末時点で集計します。",
				"\n\n",
				"## 地域別 AUM (Q3 末、yen 換算)",
				"\n",
				"- **APAC**: ¥ 4,820B、",
				"YoY **+14.5%**", "[1]",
				"\n",
				"  - 新興市場の equity allocation 増 (+340 bps)",
				"\n",
				"  - HNW client onboarding 進捗が前倒し",
				"\n",
				"- **EMEA**: ¥ 3,610B、",
				"YoY **+3.1%**",
				"\n",
				"  - FX neutral 換算では +5.8%",
				"\n",
				"  - DACH 地域の institutional flow が下支え",
				"\n",
				"- **Americas**: ¥ 5,940B、",
				"YoY **+7.2%**", "[2]",
				"\n",
				"  - LATAM の private credit demand が拡大",
				"\n\n",
				"## 主要なアロケーション変化",
				"\n\n",
				"> 過去 12 ヶ月で fixed income への配分が ",
				"**+180 bps** 増、",
				"対称的に equity 配分が ",
				"**-110 bps** 減。",
				"リスクプロファイルは",
				"**moderate-conservative** にシフト。",
				"\n\n",
				"## ウォッチポイント",
				"\n",
				"- USD/JPY のヒストリカル相関が崩れた場合、",
				"EMEA セグメントの translation 影響が拡大",
				"\n",
				"- APAC の onboarding ペースは ",
				"Q4 に正常化見込み (現状 +28% above run-rate)",
				"\n\n",
				"[1] aum-tracker/apac-q3-2026 rev=8a1",
				"\n",
				"[2] americas/private-credit-flow-summary",
			},
		},
		{
			Prompt:   "今四半期の NIM と cost-to-income ratio を peer と比較し、相対ポジションを評価してください。",
			Thinking: "peer データセットを照合しています",
			Chunks: []string{
				"NIM と cost-to-income ratio の",
				"peer ベンチマークを",
				"Q3 末データで整理します。",
				"\n\n",
				"## 当行と peer (上位 6 行) の比較",
				"\n\n",
				"| 指標 | 当行 | peer 中央値 | spread |",
				"\n",
				"| --- | ---: | ---: | ---: |",
				"\n",
				"| NIM | **1.84%** | 1.71% | **+13 bps** |",
				"\n",
				"| Cost-to-Income | **52.8%** | 55.4% | **-260 bps** |",
				"\n",
				"| ROE (annualised) | **11.2%** | 9.8% | **+140 bps** |",
				"\n\n",
				"## 観察",
				"\n\n",
				"> NIM 優位の主因は ",
				"deposit franchise の duration が長く、",
				"policy rate hike サイクル後半でも",
				"asset repricing が継続した点[1]。",
				"\n\n",
				"ただし向こう 2 四半期で ",
				"deposit beta の上昇が想定され、",
				"NIM の **-15 から -25 bps** ",
				"圧縮シナリオが基準線。",
				"\n\n",
				"## 推奨アクション",
				"\n",
				"- fixed-rate asset の duration extension を継続検討",
				"\n",
				"- non-NII の比率を **+150 bps** ",
				"引き上げる中期方針を維持",
				"\n",
				"- peer ベンチの再キャリブレーションを",
				"Q4 中に実施 (新規 entrant 2 行を含める)",
				"\n\n",
				"[1] alm-desk/deposit-beta-curves-q3 rev=2c9",
			},
		},
	}
}

func responsesDegraded() []*Response {
	return []*Response{
		{
			Prompt:   "直近 30 分間の order routing latency 上昇について、主要因を整理してください。",
			Thinking: "telemetry を時系列で集約しています",
			Chunks: []string{
				"直近 30 分間の ",
				"order routing latency 上昇について、",
				"主要因を整理します。",
				"\n\n",
				"## 観測サマリー",
				"\n",
				"- p99 latency: **112ms → 384ms** (3.4x)",
				"\n",
				"- 影響 venue: **TSE / SGX / HKEX** (3 of 9)",
				"\n",
				"- 影響 instrument: equity cash, listed derivatives",
				"\n",
				"- 開始時刻: 14:08 JST (継続中)",
				"\n\n",
				"## 主要因 (推定)",
				"\n\n",
				"> APAC の market data feed multiplexer ",
				"(`feed-mux-04`) で ",
				"**socket back-pressure** が観測されており、",
				"downstream の order matcher にも",
				"knock-on の影響が出ている[1]。",
				"\n\n",
				"## 推奨対応",
				"\n",
				"1. `feed-mux-04` を `feed-mux-05` (待機) に ",
				"switch over (RTO 30 秒)",
				"\n",
				"2. 影響 venue 向けの ",
				"**aggressive sweep を一時停止**、",
				"passive のみに切り替え",
				"\n",
				"3. 並行で root cause 分析を継続",
				"\n\n",
				"[1] obs/feed-mux-04-backpressure rev=now",
			},
		},
	}
}

func responsesIncident() []*Response {
	return []*Response{
		{
			Prompt:   "本日 14:32 JST に発生した settlement 異常について、影響範囲と counterparty exposure を要約してください。",
			Thinking: "incident snapshot を構築しています",
			Chunks: []string{
				"本日 **14:32 JST** に発生した ",
				"settlement 異常について、",
				"影響範囲と counterparty exposure を要約します。",
				"\n\n",
				"## 事象サマリー",
				"\n",
				"- 発生時刻: **14:32:11 JST**",
				"\n",
				"- 検知経路: automated reconciliation alert",
				"\n",
				"- 影響 trade 件数: **1,847 件** ",
				"(うち matched: 1,412 / unmatched: 435)",
				"\n",
				"- 関連 currency: JPY, USD, EUR, GBP",
				"\n",
				"- 影響 notional: **¥ 142.6B** (gross)",
				"\n\n",
				"## Counterparty Exposure",
				"\n\n",
				"> 上位 3 counterparty で ",
				"影響 notional の **78.4%** を占める。",
				"いずれも investment grade、",
				"現時点で credit event なし[1]。",
				"\n\n",
				"- counterparty A: **¥ 52.1B** (36.5%)",
				"\n",
				"- counterparty B: **¥ 38.7B** (27.1%)",
				"\n",
				"- counterparty C: **¥ 21.0B** (14.7%)",
				"\n\n",
				"## 推定 root cause",
				"\n\n",
				"settlement instruction generation の",
				"**timezone offset** が ",
				"DST 切替に伴い ",
				"**T+1 → T+0** に誤配信。",
				"結果として cut-off 前に instruction 到達せず、",
				"fail-to-settle 状態に[2]。",
				"\n\n",
				"## 即時対応 (進行中)",
				"\n",
				"1. ★ unmatched 435 件を ",
				"**手動 reconcile キュー** に投入 (進捗 62%)",
				"\n",
				"2. ★ 影響 counterparty に ",
				"**bilateral notification** 発信 (完了)",
				"\n",
				"3. ★ regulator (FSA / SEC / FCA) への ",
				"**incident report** 起案 (T+0 内に提出予定)",
				"\n",
				"4. ★ 翌営業日の funding requirement を ",
				"**+¥ 38B** に引き上げ",
				"\n\n",
				"[1] credit-desk/cp-watchlist rev=live",
				"\n",
				"[2] platform/settle-orchestrator-incident-i20260510-1432",
			},
		},
		{
			Prompt:   "FX exposure breach の root cause analysis を、関連 trade 群と reconciliation の観点で進めてください。",
			Thinking: "trade ledger を照合しています",
			Chunks: []string{
				"FX exposure breach の ",
				"root cause analysis を、",
				"関連 trade 群と reconciliation の観点で進めます。",
				"\n\n",
				"## Breach サマリー",
				"\n",
				"- 通貨ペア: **USD/JPY**",
				"\n",
				"- limit: ¥ 80B (notional, intraday)",
				"\n",
				"- 観測値: **¥ 112.4B** (limit 比 +40.5%)",
				"\n",
				"- 持続時間: 約 8 分 (14:34 - 14:42 JST)",
				"\n",
				"- 関連 desk: APAC FX, Treasury",
				"\n\n",
				"## 関連 trade 群 (上位)",
				"\n\n",
				"> 単一の large block (notional ¥ 38B) が ",
				"**hedge offset の execution timing** からズレ、",
				"intraday limit を超過[1]。",
				"\n\n",
				"- trade-id `T26050100412`: ",
				"USD 380M, executed 14:33:54",
				"\n",
				"- trade-id `T26050100417`: ",
				"EUR 240M (cross hedge), ",
				"scheduled 14:33:55 → ",
				"**executed 14:42:07** (delay 8m12s)",
				"\n\n",
				"## Root cause (暫定)",
				"\n\n",
				"hedge engine の ",
				"FX latency が settlement 異常の影響で ",
				"**queue depth 12,800** に到達し、",
				"match orchestrator が",
				"throttle に入った[2]。",
				"\n\n",
				"## 暫定アクション",
				"\n",
				"1. ★ **manual hedge override** を投入し ",
				"exposure を限度内に復元 (完了)",
				"\n",
				"2. ★ FX desk の **intraday limit を tighten** (×0.7)",
				"\n",
				"3. ★ regulatory reportable event として ",
				"compliance に escalation 済",
				"\n\n",
				"[1] fx-desk/breach-i20260510-1434",
				"\n",
				"[2] platform/match-orch-throttle-correlation",
			},
		},
	}
}

func responsesRecovery() []*Response {
	return []*Response{
		{
			Prompt:   "settlement queue の drain progress と、affected trade の post-mortem priority を整理してください。",
			Thinking: "post-mortem シートを下書き中",
			Chunks: []string{
				"settlement queue の ",
				"drain progress と、",
				"affected trade の ",
				"post-mortem priority を整理します。",
				"\n\n",
				"## Drain Progress",
				"\n",
				"- 対象件数: **1,847 件** (incident 由来)",
				"\n",
				"- 既 reconciled: **1,812 件** (98.1%)",
				"\n",
				"- 残: **35 件** (manual review)",
				"\n",
				"- 推定完了: T+0 17:30 JST 目処",
				"\n\n",
				"## Post-mortem priority (drafting)",
				"\n\n",
				"> high priority は **3 件**、",
				"いずれも自動 reconcile 不能。",
				"それぞれ counterparty との",
				"bilateral confirm が必要[1]。",
				"\n\n",
				"1. **P1**: counterparty A 由来の ",
				"duplicate instruction (¥ 12B)",
				"\n",
				"2. **P1**: counterparty C 由来の ",
				"currency mismatch (¥ 4.8B)",
				"\n",
				"3. **P2**: 内部 ledger との timestamp 不整合 ",
				"(notional 影響なし、metadata のみ)",
				"\n\n",
				"## 復旧後の checks (パス)",
				"\n",
				"- ✓ counterparty exposure: limit 内 (margin 18% headroom)",
				"\n",
				"- ✓ FX intraday: 全 currency pair で limit 復元",
				"\n",
				"- ✓ regulatory reporting: ",
				"T+0 内 deadline に間に合う見込み",
				"\n\n",
				"[1] postmortem/i20260510-1432-bilateral-tracker",
			},
		},
	}
}

// ============ Right top: metrics ============

var Metrics = []string{
	"quote.feed.rps        ",
	"order.book.depth      ",
	"match.latency.p50     ",
	"match.latency.p99     ",
	"fail.settle.cnt       ",
	"fx.spread.bps.usdjpy  ",
	"fx.spread.bps.eurusd  ",
	"var.95.intraday       ",
	"daily.pnl.aggr        ",
	"position.delta.fx     ",
	"margin.usage.pct      ",
	"liquidity.bps         ",
	"feed.lag.us           ",
	"credit.exposure.cp.a  ",
	"credit.exposure.cp.b  ",
	"trade.tps             ",
	"repo.notional.b       ",
	"limit.utilisation.pct ",
	"queue.depth.match     ",
	"circuit.open.count    ",
	"err.timeout.5m        ",
	"reconcile.unmatched   ",
}

// Metric keys (without trailing whitespace) that go wild during incident
var SpikeMetricKeys = map[string]bool{
	"fail.settle.cnt":      true,
	"match.latency.p99":    true,
	"queue.depth.match":    true,
	"err.timeout.5m":       true,
	"circuit.open.count":   true,
	"fx.spread.bps.usdjpy": true,
	"reconcile.unmatched":  true,
}

// ============ Right top: dialogs ============

var DialogsNormal = []string{
	"SYNC WITH UPSTREAM         region=ap-northeast-1",
	"RELOADING CONFIGURATION    config-version=v3.184",
	"SNAPSHOT PERSISTED         lag=312ms",
	"LEASE ACQUIRED             holder=primary node-04",
	"INDEX REBALANCED           shards=64 -> 64",
}
var DialogsDegraded = []string{
	"RECONNECTING TO UPSTREAM   svc=feed-mux-04        attempt 2 / 5",
	"WIDENING SPREAD WATCH      pair=USD/JPY,EUR/USD",
	"BACKPRESSURE OBSERVED      svc=order-router       depth=6800",
	"DEGRADED MODE: VENUE LIST  TSE / SGX / HKEX",
}
var DialogsIncident = []string{
	"ACQUIRING LEASE            svc=settlement-svc     attempt 4 / 8",
	"VERIFYING SIGNATURE        kms=hsm-04             retry",
	"ESCALATING TO P1           channel=#war-room-fin",
	"FAILOVER PRIMARY -> STBY   region=ap-northeast-1  in progress",
	"RECONCILING UNMATCHED      pending=435            window=10m",
}
var DialogsRecovery = []string{
	"FAILOVER COMPLETED         primary=node-stby-02",
	"QUEUE DRAIN PROGRESS       1812 / 1847  (98.1%)",
	"REGULATORY REPORT FILED    fsa, sec, fca",
	"POST-MORTEM SCHEDULED      T+1  09:00 JST",
}

// ============ Right bottom: log vocab ============

var Services = []string{
	"trade-engine", "settlement-svc", "risk-monitor", "fx-router",
	"position-keeper", "margin-calc", "compliance-gw", "quote-feed",
	"order-router", "clearing-bridge", "fundsflow-svc", "ledger-writer",
	"reconcile-bot", "treasury-router", "capital-advisor", "limit-checker",
	"credit-cache", "audit-stream", "exposure-aggregator", "rates-curve",
}

var EventsInfo = []string{
	"quote.received", "order.matched", "trade.executed",
	"position.updated", "margin.recomputed", "settlement.confirmed",
	"fx.swap.committed", "capital.headroom.checked",
	"hedge.delta.balanced", "var.recalculated", "ladder.repriced",
	"repo.rolled", "clearing.batch.flushed",
	"snapshot.persisted", "feature.evaluated",
}

var EventsDebug = []string{
	"cache.miss", "cache.hit", "store.commit",
	"queue.enqueued", "queue.consumed", "stream.advance",
	"lease.acquired", "lease.expired", "shard.rebalanced",
	"config.applied", "consumer.lag.observed",
}

var EventsWarn = []string{
	"latency.budget.exceeded", "spread.widening", "throughput.degraded",
	"queue.backpressure.observed", "circuit.half-open",
	"rate-limit.threshold.hit", "depth.thinned",
	"duplicate.suppressed", "session.timeout.warning",
}

var EventsError = []string{
	"store.rollback", "circuit.open",
	"settlement.failed", "fx.exposure.breach",
	"match.timeout", "limit.breach",
	"reconcile.mismatch", "auth.token.refused",
	"depend.unavailable", "consumer.stalled",
}

var EventsFatal = []string{
	"feed.disconnected", "primary.lost", "quorum.lost",
	"data.integrity.violation", "deadlock.detected",
}

var AlertLines = []string{
	"★ ALERT  fx.exposure.breach    svc=fx-router       venue=APAC      pair=USD/JPY    ack required",
	"★ ALERT  settlement.fail.spike svc=settlement-svc  region=ap-ne-1  affected=435    ack required",
	"★ ALERT  margin.headroom.low   svc=margin-calc     desk=APAC-FX    headroom=4%     ack required",
	"★ ALERT  queue.depth.crit      svc=match-engine    shard=12        depth=14823     ack required",
	"★ ALERT  primary.replica.lost  svc=ledger-writer   region=ap-ne-1                  ack required",
	"★ ALERT  counterparty.review   svc=credit-cache    cp=B            limit-util=92%  ack required",
}
